# Generated by Django 3.2.16 on 2022-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=250)),
                ('i', models.ImageField(upload_to='pics')),
                ('d', models.TextField()),
            ],
        ),
    ]
